version: '3'

services:
  go-producer:  
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: my-producer  
    command: ["./producer"]
    network_mode: "host"