version: '3'

services:
  producer:  
    build: .
    env_file:
      - .env
    command: ["./producer"]
    networks:
      - kafka_frontend

networks:
  kafka_frontend:
    external: true  # Используем внешнюю сеть
    name: kafka_frontend