version: '3.9'

services:
  producer:  
    build: .
    container_name: producer
    env_file:
      - .env
    command: ["./producer"]
    expose:
      - "8888"    # метрики Prometheus
    networks:
      - kafka_frontend

networks:
  kafka_frontend:
    external: true  # Используем внешнюю сеть
    name: kafka_frontend
