version: '3.9'

services:
  consumer:  
    build: .
    env_file:
      - .env
    command: ["./consumer"]
    stop_grace_period: 65s
    ports:
      - "8889:8889"  # метрики Prometheus
    networks:
      - kafka_frontend
      - monitoring_monitoring

networks:
  kafka_frontend:
    external: true  # Используем внешнюю сеть
    name: kafka_frontend
  monitoring_monitoring:
    external: true
    name: monitoring_monitoring  # должно совпадать с сетью в monitoring/docker-compose.yml