version: '3'

services:
  go-consumer:  
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    image: my-consumer  
    command: ["./consumer-L0"]
    network_mode: "host"
