version: '3'

services:
  consumer:  
    build: .
    env_file:
      - .env
    command: ["./consumer"]
    stop_grace_period: 45s
    networks:
      - kafka_frontend

networks:
  kafka_frontend:
    external: true  # Используем внешнюю сеть
    name: kafka_frontend
