global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'Orders-Info-Menedger'

scrape_configs:
  # Продюсер (будет на порту 8888)
  - job_name: 'producer'
    static_configs:
      - targets: ['producer:8888']    # Имя контейнера из docker
    scrape_interval: 1s
    metrics_path: '/metrics'

  # Консумер (будет на порту 8889)
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8889']
    scrape_interval: 1s
    metrics_path: '/metrics'

  # Сервисы (напрямую)
  - job_name: 'order-service'
    static_configs:
      - targets: ['service1:8890', 'service2:8890', 'service3:8890', 'service4:8890', 'service5:8890']
    scrape_interval: 1s
    metrics_path: '/metrics'

