version: '3.9'

services:
  
  delayed-notifier:
    build: .
    container_name: delayed-notifier
    ports:
      - ${SERVICE_PORT}:8081
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
      rabbitmq:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - notifier-network

  postgres:
    image: postgres:16
    container_name: ${DB_HOST_NAME:-postgres}
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s    
    networks:
      - notifier-network

  redis:
    image: redis:7
    container_name: ${REDIS_HOST_NAME:-redis}
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TTL=${REDIS_TTL}
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s    
    networks:
      - notifier-network

  rabbitmq:
    image: rabbitmq:4.0
    container_name: ${RABBIT_HOST_NAME:-rabbitmq}
    ports:
      - ${RABBIT_PORT}:5672      # AMQP
      - "15672:15672"            # Web UI
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=${RABBIT_VHOST}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s 
    networks:
      - notifier-network

volumes:
  postgres-db:
  redis_data:
  rabbitmq_data:

networks:
  notifier-network:
    driver: bridge