name: Order-Service

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x]
  
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Display Go version
      run: go version

    - name: Install dependencies
      run: go mod tidy
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Run producer unit tests
      run: |
        go test -run ^TestGetEnvString$ ./...
        go test -run ^TestGetEnvInt$ ./...
        go test -run ^TestReadConfigProducer$ ./...
        go test -run ^TestCreateDelivery$ ./...
        go test -run ^TestCreatePayment$ ./...
        go test -run ^TestCreateItem$ ./...
        go test -run ^TestMessageGenerate$ ./...
        go test -run ^TestMessageGenerateCount$ ./...
    
    - name: Run producer integration test
      env:
        CGO_ENABLED: 0
        GOOS: linux
      run: |
        go test -timeout 2m -run ^TestProduceIntegrations$ ./...

    - name: Run consumer unit tests
      run: |
        go test -run ^TestGetEnvString$ ./...
        go test -run ^TestGetEnvInt$ ./...
        go test -run ^TestReadConfig$ ./...
        go test -run ^TestExtractOrderUID$ ./...
    
    - name: Run consumer integration test
      env:
        CGO_ENABLED: 0
        GOOS: linux
      run: |
        go test -timeout 2m -run ^TestConsumPipelineIntegrations$ ./...



        
    - name: Run DB
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestDB$ ./tests 
        
    - name: Run NextDate
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestNextDate$ ./tests 
        
    - name: Run DB
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestDB$ ./tests 
                
    - name: Run NextDate
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestNextDate$ ./tests 
    
    - name: Run AddTask
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestAddTask$ ./tests 

    - name: Run TestTasks
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestTasks$ ./tests

    - name: Run TestTask
      run: |
        CGO_ENABLED=0 GOOS=linux go run main.go &
        sleep 100
        go test -run ^TestTask$ ./tests

    - name: Run TestEditTask
      run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 100
          go test -run ^TestEditTask$ ./tests

    - name: Run TestDone
      run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 100
          go test -run ^TestDone$ ./tests

    - name: Run TestDelTask
      run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 100
          go test -run ^TestDelTask$ ./tests

    - name: Run test
      run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 100
          go test ./tests
