name: Order-Service CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ["service", "producer", "consumer"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go with cache
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        cache: true
        cache-dependency-path: ${{ matrix.module }}/go.sum
    
    - name: Display Go version
      run: go version

    - name: Install dependencies
      working-directory: ${{ matrix.module }}
      run: go mod download

    - name: Run unit tests
      working-directory: ${{ matrix.module }}
      run: go test -v -short ./...

    - name: Vet
      working-directory: ${{ matrix.module }}
      run: go vet ./...

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run golangci-lint
      working-directory: ${{ matrix.module }}
      run: golangci-lint run ./...
 
  integration-tests:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'
        cache: false
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    
    - name: Start Docker
      run: |
        sudo systemctl start docker || true
        sudo chmod 666 /var/run/docker.sock || true
        docker version
    
    - name: Run producer integration tests
      working-directory: ./producer
      run: |
        go mod download
        go test -v -timeout 2m -run ^TestProduceIntegrations$ ./...
    
    - name: Run consumer integration tests
      working-directory: ./consumer
      run: |
        go mod download
        go test -v -timeout 2m -run ^TestConsumPipelineIntegrations$ ./...