version: '3.9'

services:
  
  # балансировщик nginx
  nginx:
    image: nginx:1.29.4-alpine
    container_name: ${SERVICE_HOST_NAME:-nginx}
    environment:
      - CLIENT_MAX_BODY_SIZE=10m  
    ports:
      - "${SERVICE_PORT:-8081}:8081"    # веб-интерфейс
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service1
      - service2
      - service3
      - service4
      - service5
    networks:
      - backend
      - kafka_frontend
    restart: unless-stopped

  # пять инстансов сервиса
  service1:
    build: .
    container_name: ${SERVICE_HOST_NAME:-service}1
    hostname: ${SERVICE_HOST_NAME:-service}1
    expose:
      - "8081"
      - "8890"    # метрики Prometheus
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - backend
      - kafka_frontend
    environment:
      - INSTANCE_ID=1

  service2:
    build: .
    container_name: ${SERVICE_HOST_NAME:-service}2
    hostname: ${SERVICE_HOST_NAME:-service}2
    expose:
      - "8081"
      - "8890"    # метрики Prometheus
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - backend
      - kafka_frontend
    environment:
      - INSTANCE_ID=2

  service3:
    build: .
    container_name: ${SERVICE_HOST_NAME:-service}3
    hostname: ${SERVICE_HOST_NAME:-service}3
    expose:
      - "8081"
      - "8890"    # метрики Prometheus
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - backend
      - kafka_frontend
    environment:
      - INSTANCE_ID=3

  service4:
    build: .
    container_name: ${SERVICE_HOST_NAME:-service}4
    hostname: ${SERVICE_HOST_NAME:-service}4
    expose:
      - "8081"
      - "8890"    # метрики Prometheus
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - backend
      - kafka_frontend
    environment:
      - INSTANCE_ID=4

  service5:
    build: .
    container_name: ${SERVICE_HOST_NAME:-service}5
    hostname: ${SERVICE_HOST_NAME:-service}5
    expose:
      - "8081"
      - "8890"    # метрики Prometheus
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - backend
      - kafka_frontend
    environment:
      - INSTANCE_ID=5

  postgres:
    image: postgres:16
    container_name: ${DB_HOST_NAME:-postgres}
    hostname: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=2GB"                  # увеличим кэш postgres
      - "-c"
      - "maintenance_work_mem=1GB"            # увеличим для служебных операций (быстрее создание индексов)
      - "-c"
      - "wal_buffers=128MB"                   # увеличим буфер журнала транзакций
      - "-c"
      - "max_wal_size=4GB"               
      - "-c"
      - "checkpoint_completion_target=0.9"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s    
    networks:
      - backend

  redis:
    image: redis:7
    container_name: ${REDIS_HOST_NAME:-redis}
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TTL=${REDIS_TTL}
    command: 
    - "redis-server"
    - "--maxmemory 256mb"                  # Лимит памяти
    - "--maxmemory-policy volatile-lru"    # Вытесняем только ключи с TTL
    - "--save ''"                          # Отключаем автоматический снапшот на диск (считаем, что персистентность не нужна, так как это чистый кэш)
    - "--appendonly no"                    # Отключаем AOF, так как персистентность не критична
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s    
    networks:
      - backend

volumes:
  postgres-db:
  redis_data:

networks:
  kafka_frontend:
    external: true  # Используем внешнюю сеть
    name: kafka_frontend
  backend: