services:
  service:
    build: .
    env_file:
      - .env
    container_name: ${SERVICE_HOST_NAME:-service}
    hostname: service
    ports:
      - ${SERVICE_PORT}:8081
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 
    stop_grace_period: 45s
    networks:
      - backend
      - kafka_frontend

  postgres:
    image: postgres:16
    container_name: ${DB_HOST_NAME:-postgres}
    hostname: postgres
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"            # увеличим кэш postgres
      - "-c"
      - "maintenance_work_mem=512MB"    # увеличим для служебных операций (быстрее создание индексов)
      - "-c"
      - "wal_buffers=64MB"              # увеличим буфер журнала транзакций
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s    
    networks:
      - backend

  redis:
    image: redis:7
    container_name: ${REDIS_HOST_NAME:-redis}
    hostname: redis
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TTL=${REDIS_TTL}
    command: 
    - "redis-server"
    - "--maxmemory 256mb"                  # Лимит памяти
    - "--maxmemory-policy volatile-lru"    # Вытесняем только ключи с TTL
    - "--save ''"                          # Отключаем автоматический снапшот на диск (считаем, что персистентность не нужна, так как это чистый кэш)
    - "--appendonly no"                    # Отключаем AOF, так как персистентность не критична
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s    
    networks:
      - backend

volumes:
  postgres-db:
  redis_data:

networks:
  kafka_frontend:
    external: true  # Используем внешнюю сеть
    name: kafka_frontend
  backend: